# This rule is not used by the project kb-cronjob itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the auto-remediation.t-wallace.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kb-cronjob
    app.kubernetes.io/managed-by: kustomize
  name: remediationjob-editor-role
rules:
- apiGroups:
  - auto-remediation.t-wallace.com
  resources:
  - remediationjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auto-remediation.t-wallace.com
  resources:
  - remediationjobs/status
  verbs:
  - get
