---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - auto-remediation.t-wallace.com
  resources:
  - remediationjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auto-remediation.t-wallace.com
  resources:
  - remediationjobs/finalizers
  verbs:
  - update
- apiGroups:
  - auto-remediation.t-wallace.com
  resources:
  - remediationjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
